In [1]:
import sqlite3
import pandas as pd
import ast

con=sqlite3.connect(r"C:\Users\muhmm\ipl_proj\Data\Raw\ipl.db")
def q(sql):
    return pd.read_sql_query(sql,con)

In [2]:
def run_sql_file(path):
    with open(path, 'r') as f:
        script = f.read()
    con.executescript(script)
    con.commit()
    print('ran', path)

In [3]:
run_sql_file(r"C:\Users\muhmm\ipl_proj\sql\practice\test.sql")

ran C:\Users\muhmm\ipl_proj\sql\practice\test.sql

In [4]:
q('''select * from matches;''')

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,Kolkata Knight Riders,140.0,NaN,win,BB McCullum,1,6,1,6,46.0
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,Sunrisers Hyderabad,35.0,NaN,win,Yuvraj Singh,2,1,1,2,15.0
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Rising Pune Supergiant,NaN,7.0,win,SPD Smith,4,3,4,4,36.0
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Kolkata Knight Riders,NaN,10.0,win,CA Lynn,5,6,6,6,57.0
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,NaN,6.0,win,GJ Maxwell,494,4,494,494,71.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,1529282,2026,6,Delhi,2026-04-27,Indian Premier League,39.0,male,T20,T20,...,Royal Challengers Bangalore,NaN,9.0,win,JR Hazlewood,252,1,1,1,4664.0
1208,1529283,2026,6,New Chandigarh,2026-04-28,Indian Premier League,40.0,male,T20,T20,...,Rajasthan Royals,NaN,6.0,win,D Ferreira,494,134,134,134,11389.0
1209,1529284,2026,6,Mumbai,2026-04-29,Indian Premier League,41.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,6.0,win,H Klaasen,3,2,3,2,1740.0
1210,1529285,2026,6,Ahmedabad,2026-04-30,Indian Premier League,42.0,male,T20,T20,...,Gujarat Titans,NaN,4.0,win,JO Holder,1,615,615,615,4098.0
1211,1529286,2026,6,Jaipur,2026-05-01,Indian Premier League,43.0,male,T20,T20,...,Delhi Capitals,NaN,7.0,win,KL Rahul,134,252,134,252,1409.0

In [5]:
run_sql_file(r"C:\Users\muhmm\ipl_proj\sql\practice\01_null_and_blanket.sql")

ran C:\Users\muhmm\ipl_proj\sql\practice\01_null_and_blanket.sql

In [6]:
q('''select count(*) as blank_before
from deliveries
where trim(bowler_type) = '';''')

   blank_before
0             8

In [7]:
q('''select count(*) as null_after
from v_players_clean
where field_pos_clean is null;''')

   null_after
0         700

In [8]:
run_sql_file(r"C:\Users\muhmm\ipl_proj\sql\practice\02_merge_categories.sql")

ran C:\Users\muhmm\ipl_proj\sql\practice\02_merge_categories.sql

In [9]:
q("""select distinct team_name
from teams
order by team_name;""")

                      team_name
0           Chennai Super Kings
1               Deccan Chargers
2                Delhi Capitals
3                 Gujarat Lions
4                Gujarat Titans
5          Kochi Tuskers Kerala
6         Kolkata Knight Riders
7          Lucknow Super Giants
8                Mumbai Indians
9                 Pune Warriors
10                 Punjab Kings
11             Rajasthan Royals
12       Rising Pune Supergiant
13      Rising Pune Supergiants
14  Royal Challengers Bangalore
15          Sunrisers Hyderabad

In [10]:
q("""select distinct team_name_clean
from v_teams_clean
order by team_name_clean;""")

                team_name_clean
0           Chennai Super Kings
1               Deccan Chargers
2                Delhi Capitals
3                 Gujarat Lions
4                Gujarat Titans
5          Kochi Tuskers Kerala
6         Kolkata Knight Riders
7          Lucknow Super Giants
8                Mumbai Indians
9                 Pune Warriors
10                 Punjab Kings
11             Rajasthan Royals
12       Rising Pune Supergiant
13  Royal Challengers Bangalore
14          Sunrisers Hyderabad

In [11]:
run_sql_file(r"C:\Users\muhmm\ipl_proj\sql\practice\03_venue_names.sql")

ran C:\Users\muhmm\ipl_proj\sql\practice\03_venue_names.sql

In [12]:
run_sql_file(r"C:\Users\muhmm\ipl_proj\sql\practice\04_dedupe_venues.sql")

ran C:\Users\muhmm\ipl_proj\sql\practice\04_dedupe_venues.sql

In [13]:
q("""select venue_clean, count(*) as matches
from v_matches_venue
group by venue_clean
order by matches desc limit 10;""")

                           venue_clean  matches
0                     Wankhede Stadium      130
1                         Eden Gardens      104
2               MA Chidambaram Stadium       95
3                M Chinnaswamy Stadium       89
4   Rajiv Gandhi International Stadium       87
5               Sawai Mansingh Stadium       66
6                     Feroz Shah Kotla       60
7  Dubai International Cricket Stadium       46
8                 Arun Jaitley Stadium       41
9                Narendra Modi Stadium       37

In [14]:
q("""select count(*) as rows,count(distinct venue) as names
from venues;""")

   rows  names
0    63     59

In [15]:
q("""select count(*) as venue,city
from venues
group by venue
order by count(*) desc limit 10;""")

   venue       city
0      2        NaN
1      2     Mohali
2      2        NaN
3      2     Mumbai
4      1  Abu Dhabi
5      1     Mumbai
6      1     Mumbai
7      1     Nagpur
8      1  Centurion
9      1       Pune

In [16]:
run_sql_file(r"C:\Users\muhmm\ipl_proj\sql\practice\05_city_fallback.sql")

ran C:\Users\muhmm\ipl_proj\sql\practice\05_city_fallback.sql

In [17]:
q("""select city_clean from v_city_clean
where city_clean is null;""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [18]:
q("""select city_clean from v_city_clean
where city_clean = 'UNKNOWN';""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [19]:
q(""" SELECT city_clean FROM v_city_clean
WHERE city_clean IN('UNKNOWN');""")

Empty DataFrame
Columns: [city_clean]
Index: []

In [20]:
q(""" SELECT city_clean FROM v_city_clean
LIMIT 5;""")

  city_clean
0  Bangalore
1  Hyderabad
2       Pune
3     Rajkot
4     Indore

In [21]:
run_sql_file(r"C:\Users\muhmm\ipl_proj\sql\practice\06_season_year.sql")

ran C:\Users\muhmm\ipl_proj\sql\practice\06_season_year.sql

In [22]:
q(""" select season,
         count(*) as matches
from matches
where season ='2020/21'
group by season;""")

    season  matches
0  2020/21       60

In [23]:
q(""" select distinct season, season_year
from v_season
where season ='2020/21';""")

    season  season_year
0  2020/21         2020

In [24]:
run_sql_file(r"C:\Users\muhmm\ipl_proj\sql\practice\07_win_definition.sql")

ran C:\Users\muhmm\ipl_proj\sql\practice\07_win_definition.sql

In [25]:
run_sql_file(r"C:\Users\muhmm\ipl_proj\sql\practice\08_matches_clean.sql")

ran C:\Users\muhmm\ipl_proj\sql\practice\08_matches_clean.sql

In [26]:
q("""SELECT * from matches_clean;""")

,match_id,venue_clean,city_clean,season_year,result,match_winner,player_of_match,toss_winner,toss_decision
0,335982,M Chinnaswamy Stadium,Bangalore,2008,win,Kolkata Knight Riders,BB McCullum,Royal Challengers Bangalore,field
1,1082591,Rajiv Gandhi International Stadium,Hyderabad,2017,win,Sunrisers Hyderabad,Yuvraj Singh,Royal Challengers Bangalore,field
2,1082592,Maharashtra Cricket Association Stadium,Pune,2017,win,Rising Pune Supergiant,SPD Smith,Rising Pune Supergiant,field
3,1082593,Saurashtra Cricket Association Stadium,Rajkot,2017,win,Kolkata Knight Riders,CA Lynn,Kolkata Knight Riders,field
4,1082594,Holkar Cricket Stadium,Indore,2017,win,Punjab Kings,GJ Maxwell,Punjab Kings,field
...,...,...,...,...,...,...,...,...,...
1063,1529279,Sawai Mansingh Stadium,Jaipur,2026,win,Sunrisers Hyderabad,Ishan Kishan,Sunrisers Hyderabad,field
1064,1529280,MA Chidambaram Stadium,Chennai,2026,win,Gujarat Titans,K Rabada,Gujarat Titans,field
1065,1529282,Arun Jaitley Stadium,Delhi,2026,win,Royal Challengers Bangalore,JR Hazlewood,Royal Challengers Bangalore,field
1066,1529284,Wankhede Stadium,Mumbai,2026,win,Sunrisers Hyderabad,H Klaasen,Mumbai Indians,bat
1067,1529286,Sawai Mansingh Stadium,Jaipur,2026,win,Delhi Capitals,KL Rahul,Rajasthan Royals,bat

In [27]:
d= pd.read_sql('select * from deliveries where fielders_involved is not null', con)
d['fielders']= d['fielders_involved'].apply(ast.literal_eval)

d=d.explode('fielders')

d['fielders'].value_counts().head()

fielders
MS Dhoni          258
KD Karthik        228
RV Uthappa        169
AB de Villiers    148
V Kohli           142
Name: count, dtype: int64